web/WebOpenDoor/WebOpenDoor/Controllers/AuthorizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using WebOpenDoor.Context;
using WebOpenDoor.ViewModels;

namespace WebOpenDoor.Controllers
{
    public class AuthorizeController : Controller
    {
        private readonly WebDbContext _context;
        public AuthorizeController(WebDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Login(UserLoginViewModel user)
        {
            if (!ModelState.IsValid) 
                return View(user);

            var resultLogin = _context.User.FirstOrDefault(w => w.Login.ToUpper() == user.Login.ToUpper() && w.Password == user.Password.ToUpper());

            if(resultLogin != null)
            {
                var identity = new ClaimsIdentity("ApplicationCookie");
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, resultLogin.Login));
                identity.AddClaim(new Claim(ClaimTypes.Name, resultLogin.UserName));
                identity.AddClaim(new Claim(ClaimTypes.Sid, resultLogin.UserId.ToString()));

                var principalClaims = new ClaimsPrincipal(identity);
                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    IsPersistent = true,
                    ExpiresUtc = DateTime.UtcNow.AddHours(15)
                };

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principalClaims, authProperties);
                return RedirectToAction("Index", "Control");
            }

            return RedirectToAction("Login");
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

web/WebOpenDoor/WebOpenDoor/Controllers/ControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebOpenDoor.Controllers
{
    [Authorize]
    public class ControlController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

web/WebOpenDoor/WebOpenDoor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebOpenDoor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/js/dataTables/datatables.min.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/dataTables/datatables.min.js"></script>
    <script src="~/js/dataTables/DataTables-1.10.20/js/dataTables.bootstrap4.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Control" asp-action="Index">
                    <i class="fa fa-door-open"></i>OpenDoor
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse w-75 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-user"></i>
                                    @User.Identity.Name
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="@Url.Action("Logout", "Authorize")">
                                        <i class="fa fa-sign-out-alt"></i> Logout
                                    </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Modal" />
            <div class="col-md-12">
                <div id="msgAjax"></div>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebOpenDoor
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/71cf727fe8.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

web/WebOpenDoor/WebOpenDoor/Views/Shared/_Modal.cshtml
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalBody">

            </div>
            <div class="modal-footer" id="modalFooter">

            </div>
        </div>
    </div>
</div>