web/WebOpenDoor/WebOpenDoor/Controllers/AccessLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebOpenDoor.Context;
using WebOpenDoor.Controllers.Base;
using WebOpenDoor.Models;

namespace WebOpenDoor.Controllers
{
    [Authorize]
    public class AccessLogController : BaseController
    {
        private readonly WebDbContext _webDbContext;
        public AccessLogController(WebDbContext webDbContext)
        {
            _webDbContext = webDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult ObterLogs()
        {
            var accessLogs = _webDbContext.DoorAccessLog.ToList();
            accessLogs.ForEach(f =>
            {
                f.Door = _webDbContext.Door.Find(f.DoorId);
                f.User = _webDbContext.User.FirstOrDefault(w => w.UserRfId ==  f.UserRfId);

            });

            return Json(new { data = accessLogs });
        }
    }
}

web/WebOpenDoor/WebOpenDoor/Controllers/ControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebOpenDoor.Controllers
{
    [Authorize]
    public class ControlController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

web/WebOpenDoor/WebOpenDoor/Controllers/DoorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebOpenDoor.Context;
using WebOpenDoor.Controllers.Base;
using WebOpenDoor.Models;

namespace WebOpenDoor.Controllers
{
    [Authorize]
    public class DoorController : BaseController
    {
        private readonly WebDbContext _webDbContext;
        public DoorController(WebDbContext webDbContext)
        {
            _webDbContext = webDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult ObterDoors()
        {
            var doors = _webDbContext.Door.Where(w => w.Active);
            return Json(new { data = doors });
        }

        public PartialViewResult ObterDoorForm(int doorId)
        {
            Door porta = null;
            if (doorId > 0)
                porta = _webDbContext.Door.Find(doorId);

            return PartialView("~/Views/Door/Partials/_ModalDoorForm.cshtml", porta);
        }

        public JsonResult SalvarDoor(Door porta)
        {
            try
            {
                if (porta.DoorId > 0)
                    _webDbContext.Door.Update(porta);
                else
                    _webDbContext.Door.Add(porta);

                _webDbContext.SaveChanges();

                return ObterJsonMessage(true);
            }
            catch (Exception ex)
            {
                return ObterJsonMessage(false, ex.Message);
            }
        }

        public string ObterNomeDoor(int doorId)
        {
            var door = _webDbContext.Door.Find(doorId);
            return door?.Nome;
        }

        public JsonResult DeletarDoor(int doorId)
        {
            try
            {
                var porta = _webDbContext.Door.Find(doorId);
                porta.Active = false;
                _webDbContext.Door.Update(porta);
                _webDbContext.SaveChanges();

                return ObterJsonMessage(true);
            }
            catch (Exception ex)
            {
                return ObterJsonMessage(false, ex.Message);
            }
        }
    }
}

web/WebOpenDoor/WebOpenDoor/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebOpenDoor.Context;
using WebOpenDoor.Controllers.Base;
using WebOpenDoor.Models;

namespace WebOpenDoor.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private readonly WebDbContext _webDbContext;
        public UserController(WebDbContext webDbContext)
        {
            _webDbContext = webDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult ObterUsers()
        {
            var users = _webDbContext.User.Where(w => w.Active).ToList();
            var doors = _webDbContext.Door.Where(w => w.Active).ToList();

            foreach (var user in users)
            {
                var idPermitidas = _webDbContext.DoorPermission.Where(w => w.UserRfId == user.UserRfId).Select(s => s.DoorId);
                user.Doors = doors.Where(w => idPermitidas.Contains(w.DoorId));
            }
            return Json(new { data = users });
        }

        public PartialViewResult ObterUserForm(int userId)
        {
            User usuario;
            if (userId > 0)
            {
                usuario = _webDbContext.User.Find(userId);
                var idPermitidas = _webDbContext.DoorPermission.Where(w => w.UserRfId == usuario.UserRfId).Select(s => s.DoorId);
                usuario.Doors = _webDbContext.Door.Where(w => idPermitidas.Contains(w.DoorId) && w.Active);
            }
            else
            {
                usuario = new User
                {
                    Doors = new List<Door>()
                };
            }
            ViewData["listaPortas"] = _webDbContext.Door.ToList();

            return PartialView("~/Views/User/Partials/_ModalUserForm.cshtml", usuario);
        }

        public JsonResult SalvarUser(User usuario)
        {
            try
            {
                List<DoorPermission> listaPermissoes = new List<DoorPermission>();
                usuario.Doors ??= new List<Door>();
                foreach(var door in usuario.Doors)
                    listaPermissoes.Add(new DoorPermission { DoorId = door.DoorId, UserRfId = usuario.UserRfId });

                if (usuario.UserId > 0)
                {
                    _webDbContext.User.Update(usuario);
                    _webDbContext.DoorPermission.RemoveRange(_webDbContext.DoorPermission.Where(w => w.UserRfId == usuario.UserRfId));
                    _webDbContext.DoorPermission.AddRange(listaPermissoes);

                    if (string.IsNullOrEmpty(usuario.Login))
                    {
                        var entityEntry = _webDbContext.Entry(usuario);
                        entityEntry.Property("Login").IsModified = false;
                        entityEntry.Property("Password").IsModified = false;
                    }
                }
                else
                {
                    _webDbContext.User.Add(usuario);
                    _webDbContext.DoorPermission.AddRange(listaPermissoes);
                }

                _webDbContext.SaveChanges();

                return ObterJsonMessage(true);
            }
            catch (Exception ex)
            {
                return ObterJsonMessage(false, ex.Message);
            }
        }

        public string ObterNomeUser(int userId)
        {
            var user = _webDbContext.User.Find(userId);
            return user?.UserName;
        }

        public JsonResult DeletarUser(int userId)
        {
            try
            {
                var usuario = _webDbContext.User.Find(userId);
                _webDbContext.DoorPermission.RemoveRange(_webDbContext.DoorPermission.Where(w => w.UserRfId == usuario.UserRfId));
                usuario.Active = false;
                _webDbContext.User.Update(usuario);
                _webDbContext.SaveChanges();

                return ObterJsonMessage(true);
            }
            catch (Exception ex)
            {
                return ObterJsonMessage(false, ex.Message);
            }
        }
    }
}

web/WebOpenDoor/WebOpenDoor/Views/Control/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-sm-4">
            <div class="wrimagecard wrimagecard-topimage">
                <a href="@Url.Action("Index", "Door")">
                    <div class="wrimagecard-topimage_header" style="background-color:  rgba(51, 105, 232, 0.1)">
                        <center><i class="fa fa-door-closed" style="color:#3369e8"> </i></center>
                    </div>
                    <div class="wrimagecard-topimage_title">
                        <h4>Portas</h4>
                        <div class="pull-right badge"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-3 col-sm-4">
            <div class="wrimagecard wrimagecard-topimage">
                <a href="@Url.Action("Index", "User")">
                    <div class="wrimagecard-topimage_header" style="background-color:  rgba(51, 105, 232, 0.1)">
                        <center><i class="fa fa-users" style="color:#3369e8"> </i></center>
                    </div>
                    <div class="wrimagecard-topimage_title">
                        <h4>Usuários</h4>
                        <div class="pull-right badge"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-3 col-sm-4">
            <div class="wrimagecard wrimagecard-topimage">
                <a href="@Url.Action("Index", "AccessLog")">
                    <div class="wrimagecard-topimage_header" style="background-color:  rgba(51, 105, 232, 0.1)">
                        <center><i class="fa fa-question-circle" style="color:#3369e8"> </i></center>
                    </div>
                    <div class="wrimagecard-topimage_title">
                        <h4>Log de Acessos</h4>
                        <div class="pull-right badge"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>